apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-tutorial-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: stackrox
    server: https://kubernetes.default.svc
  project: default
  source:
    path: PolicyTutorials/res/app-path-argo
    repoURL: https://github.com/axodevelopment/ACS-Tutorials.git
    targetRevision: main